clone:
  git:
    image: woodpeckerci/plugin-git

when:
  branch: main 
  event: [push, cron]

steps:
  build:
    image: peaceiris/mdbook:latest
    commands:
      - mdbook build

  publish:
    image: bitnami/git
    secrets: [mail, codeberg_token]
    environment:
      - MDBOOK_OUTPUT=book
    commands:
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      - cp -ar $MDBOOK_OUTPUT/. $CI_REPO_NAME/
      - cp .domains $CI_REPO_NAME || true
      - cd $CI_REPO_NAME
      - git add .
      - git commit -m "Woodpecker CI ${CI_BUILD_CREATED}"
      - git push


